# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uiFiles\exportPathPrompt.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExportPathDialog(object):
    def setupUi(self, ExportPathDialog):
        ExportPathDialog.setObjectName("ExportPathDialog")
        ExportPathDialog.resize(400, 207)
        ExportPathDialog.setStyleSheet("QPushButton {\n"
"    background-color: #dbd5c3;\n"
"}\n"
"QDialog { \n"
"   border: 1px solid black;\n"
"    background-color: #8d6535;\n"
"}\n"
"QTextEdit {\n"
"    background-color: #dbd5c3;\n"
"}")
        self.buttonBox = QtWidgets.QDialogButtonBox(ExportPathDialog)
        self.buttonBox.setGeometry(QtCore.QRect(120, 150, 161, 23))
        self.buttonBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.pathInputText = QtWidgets.QTextEdit(ExportPathDialog)
        self.pathInputText.setGeometry(QtCore.QRect(30, 80, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.pathInputText.setFont(font)
        self.pathInputText.setObjectName("pathInputText")
        self.pathLabel = QtWidgets.QLabel(ExportPathDialog)
        self.pathLabel.setGeometry(QtCore.QRect(0, 30, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.pathLabel.setFont(font)
        self.pathLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.pathLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pathLabel.setObjectName("pathLabel")
        self.exportBrowsePathButton = QtWidgets.QPushButton(ExportPathDialog)
        self.exportBrowsePathButton.setGeometry(QtCore.QRect(270, 80, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.exportBrowsePathButton.setFont(font)
        self.exportBrowsePathButton.setObjectName("exportBrowsePathButton")

        self.retranslateUi(ExportPathDialog)
        QtCore.QMetaObject.connectSlotsByName(ExportPathDialog)

    def retranslateUi(self, ExportPathDialog):
        _translate = QtCore.QCoreApplication.translate
        ExportPathDialog.setWindowTitle(_translate("ExportPathDialog", "Dialog"))
        self.pathLabel.setText(_translate("ExportPathDialog", "Enter Path for Export:"))
        self.exportBrowsePathButton.setText(_translate("ExportPathDialog", "Browse.."))
