# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uiFiles\privateKeyInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PrivateKeyInfoDialog(object):
    def setupUi(self, PrivateKeyInfoDialog):
        PrivateKeyInfoDialog.setObjectName("PrivateKeyInfoDialog")
        PrivateKeyInfoDialog.resize(581, 649)
        PrivateKeyInfoDialog.setStyleSheet("QPushButton {\n"
"    background-color: #dbd5c3;\n"
"}\n"
"QDialog { \n"
"   border: 1px solid black;\n"
"    background-color: #8d6535;\n"
"}\n"
"QTextEdit {\n"
"    background-color: #dbd5c3;\n"
"}")
        self.moreInformationLabel = QtWidgets.QLabel(PrivateKeyInfoDialog)
        self.moreInformationLabel.setGeometry(QtCore.QRect(0, 10, 581, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.moreInformationLabel.setFont(font)
        self.moreInformationLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.moreInformationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.moreInformationLabel.setObjectName("moreInformationLabel")
        self.timeLabel = QtWidgets.QLabel(PrivateKeyInfoDialog)
        self.timeLabel.setGeometry(QtCore.QRect(0, 60, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.timeLabel.setFont(font)
        self.timeLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.timeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.userIDLabel = QtWidgets.QLabel(PrivateKeyInfoDialog)
        self.userIDLabel.setGeometry(QtCore.QRect(0, 110, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.userIDLabel.setFont(font)
        self.userIDLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.userIDLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.userIDLabel.setObjectName("userIDLabel")
        self.keyIDLabel = QtWidgets.QLabel(PrivateKeyInfoDialog)
        self.keyIDLabel.setGeometry(QtCore.QRect(0, 160, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.keyIDLabel.setFont(font)
        self.keyIDLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.keyIDLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.keyIDLabel.setObjectName("keyIDLabel")
        self.algorithmLabel = QtWidgets.QLabel(PrivateKeyInfoDialog)
        self.algorithmLabel.setGeometry(QtCore.QRect(0, 210, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.algorithmLabel.setFont(font)
        self.algorithmLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.algorithmLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.algorithmLabel.setObjectName("algorithmLabel")
        self.publicKeyLabel = QtWidgets.QLabel(PrivateKeyInfoDialog)
        self.publicKeyLabel.setGeometry(QtCore.QRect(0, 260, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.publicKeyLabel.setFont(font)
        self.publicKeyLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.publicKeyLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.publicKeyLabel.setObjectName("publicKeyLabel")
        self.publicKeyTextInput = QtWidgets.QTextBrowser(PrivateKeyInfoDialog)
        self.publicKeyTextInput.setGeometry(QtCore.QRect(130, 280, 441, 151))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.publicKeyTextInput.setFont(font)
        self.publicKeyTextInput.setObjectName("publicKeyTextInput")
        self.exitButton = QtWidgets.QPushButton(PrivateKeyInfoDialog)
        self.exitButton.setGeometry(QtCore.QRect(170, 600, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        self.timeLabelInput = QtWidgets.QLabel(PrivateKeyInfoDialog)
        self.timeLabelInput.setGeometry(QtCore.QRect(140, 60, 411, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.timeLabelInput.setFont(font)
        self.timeLabelInput.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.timeLabelInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.timeLabelInput.setObjectName("timeLabelInput")
        self.userIDLabelInput = QtWidgets.QLabel(PrivateKeyInfoDialog)
        self.userIDLabelInput.setGeometry(QtCore.QRect(140, 110, 411, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.userIDLabelInput.setFont(font)
        self.userIDLabelInput.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.userIDLabelInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.userIDLabelInput.setObjectName("userIDLabelInput")
        self.keyIDLabelInput = QtWidgets.QLabel(PrivateKeyInfoDialog)
        self.keyIDLabelInput.setGeometry(QtCore.QRect(140, 160, 411, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyIDLabelInput.setFont(font)
        self.keyIDLabelInput.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.keyIDLabelInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.keyIDLabelInput.setObjectName("keyIDLabelInput")
        self.algorithmLabelInput = QtWidgets.QLabel(PrivateKeyInfoDialog)
        self.algorithmLabelInput.setGeometry(QtCore.QRect(140, 210, 411, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.algorithmLabelInput.setFont(font)
        self.algorithmLabelInput.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.algorithmLabelInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.algorithmLabelInput.setObjectName("algorithmLabelInput")
        self.privateKeyTextInput = QtWidgets.QTextBrowser(PrivateKeyInfoDialog)
        self.privateKeyTextInput.setGeometry(QtCore.QRect(130, 440, 441, 151))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.privateKeyTextInput.setFont(font)
        self.privateKeyTextInput.setObjectName("privateKeyTextInput")
        self.privateKeyLabel = QtWidgets.QLabel(PrivateKeyInfoDialog)
        self.privateKeyLabel.setGeometry(QtCore.QRect(0, 420, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.privateKeyLabel.setFont(font)
        self.privateKeyLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.privateKeyLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.privateKeyLabel.setObjectName("privateKeyLabel")
        self.exportButton = QtWidgets.QPushButton(PrivateKeyInfoDialog)
        self.exportButton.setGeometry(QtCore.QRect(310, 600, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.exportButton.setFont(font)
        self.exportButton.setObjectName("exportButton")

        self.retranslateUi(PrivateKeyInfoDialog)
        QtCore.QMetaObject.connectSlotsByName(PrivateKeyInfoDialog)

    def retranslateUi(self, PrivateKeyInfoDialog):
        _translate = QtCore.QCoreApplication.translate
        PrivateKeyInfoDialog.setWindowTitle(_translate("PrivateKeyInfoDialog", "Dialog"))
        self.moreInformationLabel.setText(_translate("PrivateKeyInfoDialog", "More Information:"))
        self.timeLabel.setText(_translate("PrivateKeyInfoDialog", "Time:"))
        self.userIDLabel.setText(_translate("PrivateKeyInfoDialog", "UserID:"))
        self.keyIDLabel.setText(_translate("PrivateKeyInfoDialog", "KeyID:"))
        self.algorithmLabel.setText(_translate("PrivateKeyInfoDialog", "Algorithm:"))
        self.publicKeyLabel.setText(_translate("PrivateKeyInfoDialog", "Public Key:"))
        self.exitButton.setText(_translate("PrivateKeyInfoDialog", "Exit"))
        self.timeLabelInput.setText(_translate("PrivateKeyInfoDialog", "placeholder"))
        self.userIDLabelInput.setText(_translate("PrivateKeyInfoDialog", "placeholder"))
        self.keyIDLabelInput.setText(_translate("PrivateKeyInfoDialog", "placeholder"))
        self.algorithmLabelInput.setText(_translate("PrivateKeyInfoDialog", "placeholder"))
        self.privateKeyLabel.setText(_translate("PrivateKeyInfoDialog", "Private Key:"))
        self.exportButton.setText(_translate("PrivateKeyInfoDialog", "Export"))
