# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uiFiles\publicKeyInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PublicKeyInfoDialog(object):
    def setupUi(self, PublicKeyInfoDialog):
        PublicKeyInfoDialog.setObjectName("PublicKeyInfoDialog")
        PublicKeyInfoDialog.resize(581, 649)
        PublicKeyInfoDialog.setStyleSheet("QPushButton {\n"
"    background-color: #dbd5c3;\n"
"}\n"
"QDialog { \n"
"   border: 1px solid black;\n"
"    background-color: #8d6535;\n"
"}\n"
"QTextEdit {\n"
"    background-color: #dbd5c3;\n"
"}")
        self.moreInformationLabel = QtWidgets.QLabel(PublicKeyInfoDialog)
        self.moreInformationLabel.setGeometry(QtCore.QRect(0, 10, 581, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.moreInformationLabel.setFont(font)
        self.moreInformationLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.moreInformationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.moreInformationLabel.setObjectName("moreInformationLabel")
        self.timeLabel = QtWidgets.QLabel(PublicKeyInfoDialog)
        self.timeLabel.setGeometry(QtCore.QRect(0, 100, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.timeLabel.setFont(font)
        self.timeLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.timeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.userIDLabel = QtWidgets.QLabel(PublicKeyInfoDialog)
        self.userIDLabel.setGeometry(QtCore.QRect(0, 160, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.userIDLabel.setFont(font)
        self.userIDLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.userIDLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.userIDLabel.setObjectName("userIDLabel")
        self.keyIDLabel = QtWidgets.QLabel(PublicKeyInfoDialog)
        self.keyIDLabel.setGeometry(QtCore.QRect(0, 220, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.keyIDLabel.setFont(font)
        self.keyIDLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.keyIDLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.keyIDLabel.setObjectName("keyIDLabel")
        self.algorithmLabel = QtWidgets.QLabel(PublicKeyInfoDialog)
        self.algorithmLabel.setGeometry(QtCore.QRect(0, 280, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.algorithmLabel.setFont(font)
        self.algorithmLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.algorithmLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.algorithmLabel.setObjectName("algorithmLabel")
        self.publicKeyLabel = QtWidgets.QLabel(PublicKeyInfoDialog)
        self.publicKeyLabel.setGeometry(QtCore.QRect(0, 340, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.publicKeyLabel.setFont(font)
        self.publicKeyLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.publicKeyLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.publicKeyLabel.setObjectName("publicKeyLabel")
        self.publicKeyTextInput = QtWidgets.QTextBrowser(PublicKeyInfoDialog)
        self.publicKeyTextInput.setGeometry(QtCore.QRect(130, 360, 441, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.publicKeyTextInput.setFont(font)
        self.publicKeyTextInput.setObjectName("publicKeyTextInput")
        self.exitButton = QtWidgets.QPushButton(PublicKeyInfoDialog)
        self.exitButton.setGeometry(QtCore.QRect(240, 600, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        self.timeLabelInput = QtWidgets.QLabel(PublicKeyInfoDialog)
        self.timeLabelInput.setGeometry(QtCore.QRect(140, 100, 411, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.timeLabelInput.setFont(font)
        self.timeLabelInput.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.timeLabelInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.timeLabelInput.setObjectName("timeLabelInput")
        self.userIDLabelInput = QtWidgets.QLabel(PublicKeyInfoDialog)
        self.userIDLabelInput.setGeometry(QtCore.QRect(140, 160, 411, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.userIDLabelInput.setFont(font)
        self.userIDLabelInput.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.userIDLabelInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.userIDLabelInput.setObjectName("userIDLabelInput")
        self.keyIDLabelInput = QtWidgets.QLabel(PublicKeyInfoDialog)
        self.keyIDLabelInput.setGeometry(QtCore.QRect(140, 220, 411, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.keyIDLabelInput.setFont(font)
        self.keyIDLabelInput.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.keyIDLabelInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.keyIDLabelInput.setObjectName("keyIDLabelInput")
        self.algorithmLabelInput = QtWidgets.QLabel(PublicKeyInfoDialog)
        self.algorithmLabelInput.setGeometry(QtCore.QRect(140, 280, 411, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.algorithmLabelInput.setFont(font)
        self.algorithmLabelInput.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.algorithmLabelInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.algorithmLabelInput.setObjectName("algorithmLabelInput")

        self.retranslateUi(PublicKeyInfoDialog)
        QtCore.QMetaObject.connectSlotsByName(PublicKeyInfoDialog)

    def retranslateUi(self, PublicKeyInfoDialog):
        _translate = QtCore.QCoreApplication.translate
        PublicKeyInfoDialog.setWindowTitle(_translate("PublicKeyInfoDialog", "Dialog"))
        self.moreInformationLabel.setText(_translate("PublicKeyInfoDialog", "More Information:"))
        self.timeLabel.setText(_translate("PublicKeyInfoDialog", "Time:"))
        self.userIDLabel.setText(_translate("PublicKeyInfoDialog", "UserID:"))
        self.keyIDLabel.setText(_translate("PublicKeyInfoDialog", "KeyID:"))
        self.algorithmLabel.setText(_translate("PublicKeyInfoDialog", "Algorithm:"))
        self.publicKeyLabel.setText(_translate("PublicKeyInfoDialog", "Public Key:"))
        self.exitButton.setText(_translate("PublicKeyInfoDialog", "Exit"))
        self.timeLabelInput.setText(_translate("PublicKeyInfoDialog", "placeholder"))
        self.userIDLabelInput.setText(_translate("PublicKeyInfoDialog", "placeholder"))
        self.keyIDLabelInput.setText(_translate("PublicKeyInfoDialog", "placeholder"))
        self.algorithmLabelInput.setText(_translate("PublicKeyInfoDialog", "placeholder"))
