# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uiFiles\receivePrompt.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReceiveDialog(object):
    def setupUi(self, ReceiveDialog):
        ReceiveDialog.setObjectName("ReceiveDialog")
        ReceiveDialog.resize(400, 207)
        ReceiveDialog.setStyleSheet("QPushButton {\n"
"    background-color: #dbd5c3;\n"
"}\n"
"QDialog { \n"
"   border: 1px solid black;\n"
"    background-color: #8d6535;\n"
"}\n"
"QTextEdit {\n"
"    background-color: #dbd5c3;\n"
"}")
        self.buttonBox = QtWidgets.QDialogButtonBox(ReceiveDialog)
        self.buttonBox.setGeometry(QtCore.QRect(120, 170, 161, 23))
        self.buttonBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.passwordInputText = QtWidgets.QTextEdit(ReceiveDialog)
        self.passwordInputText.setGeometry(QtCore.QRect(90, 110, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.passwordInputText.setFont(font)
        self.passwordInputText.setObjectName("passwordInputText")
        self.passwordLabel = QtWidgets.QLabel(ReceiveDialog)
        self.passwordLabel.setGeometry(QtCore.QRect(0, 10, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.passwordLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordLabel.setObjectName("passwordLabel")
        self.receiveKeyIDLabel = QtWidgets.QLabel(ReceiveDialog)
        self.receiveKeyIDLabel.setGeometry(QtCore.QRect(0, 70, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.receiveKeyIDLabel.setFont(font)
        self.receiveKeyIDLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.receiveKeyIDLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.receiveKeyIDLabel.setObjectName("receiveKeyIDLabel")

        self.retranslateUi(ReceiveDialog)
        QtCore.QMetaObject.connectSlotsByName(ReceiveDialog)

    def retranslateUi(self, ReceiveDialog):
        _translate = QtCore.QCoreApplication.translate
        ReceiveDialog.setWindowTitle(_translate("ReceiveDialog", "Dialog"))
        self.passwordLabel.setText(_translate("ReceiveDialog", "To Decrypt this message\n"
"you need to enter password for Key:"))
        self.receiveKeyIDLabel.setText(_translate("ReceiveDialog", "placeholder"))
